### ISSUE TITLE
Update with iOS Unified Support

### ISSUE THREAD

**Issue by jamesmontemagno** [jguertl/SharePlugin#3]
Hey there! With 1.3.1 now on stable with Unified support it would be great if you could update the plugin with this support. I created a short How To video on how to do this: https://www.youtube.com/watch?v=nF8DbL-PVKw

**Comment by JoshuaNovak919** [comment]
Any update on this?

**Comment by JoshuaNovak919** [comment]
@jamesmontemagno Has anyone updated this or done something similar? I thought about updating it and releasing it, but I haven't ever made a nuget before and even after watching the video i'm not sure what i'd need to do.

**Comment by jguertl** [comment]
Hey @JoshuaNovak919!
Feel free to create a pull request of the updated plugin. I wrote a [blog post](http://guertl.me/post/106441007780/writing-a-xamarin-forms-plugin) about publishing a Xamarin.Forms plugin as a NuGet.

**Comment by JoshuaNovak919** [comment]
@jamesmontemagno @jguertl I've been trying to update this so I can create a pull request, but I keep getting an error saying i'm missing a dll. I think it may because i'm on a mac and not using visual studio. 

**Here is the error:**

`Could not find file "/var/folders/hq/_rb34cld6yqgy0bnkv20l3hw0000gn/T/nuget/lvmj0etb.5et/lib/portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10/Xamarin.Forms.Core.dll"`

Any ideas?

**Comment by JoshuaNovak919** [comment]
I got it working by using a different fork of this project. Testing it now.

**Comment by JoshuaNovak919** [comment]
Looks like I can't build the nuget without changing a lot of code since this project was built on windows and i'm on mac. :(

**Comment by jamesmontemagno** [comment]
Fixing this now with new v2 version, available soon.

**Comment by jamesmontemagno** [comment]
https://www.nuget.org/packages/Share.Plugin.Xamarin.Forms/2.0.0-alpha1
