### ISSUE TITLE
Using OpenBrowser on iOS requires app rating of 17+

### ISSUE THREAD

**Issue by SmartyP** [jguertl/SharePlugin#47]
When submitting an app to iTunes you have to specify a rating. If the app contains an embedded web browser that allows the user to change the URL, then you have to check off "Unrestricted web access" for your app. Selecting this option automatically makes your app rating 17+. I didn't realize this during development, so I've had to pull this back out and go back to just launching the URL normally. 

I think it would be good to point this out in the readme and/or add an option to BrowserOptions that locks down the URL from being edited, or hides the URL field, on iOS.

Thanks for your consideration!

**Comment by jamesmontemagno** [comment]
I haven't had this issue at all actually and it lives in 4 of my apps on the app store today... this is strange. What did the email say from apple? We can add a browser option for sure if it exists on the sfsafariview side

**Comment by SmartyP** [comment]
I didn't submit it for review, just going by the marketplace guidelines:
https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/FirstSteps.html

A bit past halfway down the page it covers app ratings, and says next to 17+ "Unrestricted web access, such as with an embedded browser".

My bet is they normally don't catch it unless it is opening something like YouTube or Google, etc., but as someone who has had apps retroactively pulled from app stores in the past, I'm not going to risk it ;) You can find a Stack Overflow article on it here:
http://stackoverflow.com/questions/24462543/what-does-unrestricted-web-access-mean-in-itunes-connect/24462676

**Comment by jamesmontemagno** [comment]
Yeah, that is the thing is that it isn't embedded at all to be honest with you which is why we changed it to SFSafariView. As it is outside of your app.

Reading the stack overflow:

Since the release of iOS 9 Apple has introduced SFSafariViewController which is a way of opening any URLs in the internet. This feature also has an address bar but read-only. So users can't surf the Web without parental control. It also inherits content blocking from Safari (ads, explicit content, etc.). I am highly positive by using SFSafariViewController in iOS 9 or above you still can choose 4+ as the device with parental control can't open any URLs anyway. (Let me know if I am wrong)..

The addressbar is read-only. I will look into it more, but even the Evolve app used this!

**Comment by SmartyP** [comment]
Well crap, I didn't realize the URL field was already locked down. I see that I can't edit it on iOS 9, and that on iOS 8 it launches an external browser. That's totally fine for 4+ rating.

Sorry for the unnecessary issue, in too much of a rush today. Thanks much!

**Comment by jamesmontemagno** [comment]
Ahhhhhhhh interesting, that makes sense
